import { input, password, confirm } from "@inquirer/prompts";
import { BaseModule } from "../base-module.js";
import { registerModule } from "../registry.js";
import { promptTags } from "../shared/tags.js";
import { printManual } from "../../utils/prompts.js";
import type { ModuleConfig, ExecutionResult, VerificationResult } from "../../config/types.js";
import type { DatadogClient } from "../../client/datadog-client.js";
import { writeExecutableFile, getSecureOutputDir } from "../../utils/secure-write.js";
import { escapeShellArg } from "../../utils/validators.js";

interface AzureConfig extends ModuleConfig {
  tenantName: string;
  clientId: string;
  clientSecret: string;
  subscriptionIds: string[];
  automute: boolean;
  enableCspm: boolean;
  tags: string[];
}

class AzureModule extends BaseModule {
  readonly id = "azure";
  readonly name = "Azure統合";
  readonly description = "AzureテナントとDatadogを接続";
  readonly category = "cloud" as const;
  readonly dependencies: string[] = [];

  async prompt(): Promise<AzureConfig> {
    const tenantName = await input({
      message: "Azure Tenant Name (ドメイン名):",
      validate: (v) => v.trim().length > 0 || "Tenant Nameを入力してください",
    });

    const clientId = await input({
      message: "Azure Client ID (App Registration):",
      validate: (v) => v.trim().length > 0 || "Client IDを入力してください",
    });

    const clientSecret = await password({
      message: "Azure Client Secret:",
      mask: "*",
    });

    const subsRaw = await input({
      message: "監視するSubscription ID (カンマ区切り):",
      validate: (v) => v.trim().length > 0 || "Subscription IDを入力してください",
    });
    const subscriptionIds = subsRaw.split(",").map((s) => s.trim()).filter(Boolean);

    const automute = await confirm({
      message: "VM停止時の自動ミュートを有効にしますか？",
      default: true,
    });

    const enableCspm = await confirm({
      message: "Cloud Security Posture Management (CSPM) を有効にしますか？",
      default: false,
    });

    const tags = await promptTags();

    return { tenantName, clientId, clientSecret, subscriptionIds, automute, enableCspm, tags };
  }

  async execute(config: AzureConfig, client: DatadogClient): Promise<ExecutionResult> {
    const resources = [];
    const manualSteps = [];
    const errors = [];

    try {
      await client.v1.azure.createAzureIntegration({
        body: {
          tenantName: config.tenantName,
          clientId: config.clientId,
          clientSecret: config.clientSecret,
          automute: config.automute,
          cspmEnabled: config.enableCspm,
          hostFilters: config.tags.join(","),
        },
      });

      resources.push({
        type: "azure_integration",
        id: config.tenantName,
        name: `Azure Tenant ${config.tenantName}`,
        createdAt: new Date().toISOString(),
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      errors.push(`Azure統合作成失敗: ${msg}`);
    }

    // Generate az CLI commands for prerequisites
    const azScript = generateAzSetupScript(config);
    const outputDir = getSecureOutputDir();
    const scriptPath = `${outputDir}/azure-setup.sh`;
    writeExecutableFile(scriptPath, azScript);

    manualSteps.push({
      title: "Azure App Registration & ロール付与",
      description: "App Registrationが未作成の場合、以下のスクリプトを実行してください。",
      commands: [`chmod +x ${scriptPath}`, `./${scriptPath}`],
      outputFile: scriptPath,
    });

    printManual(`Azureセットアップスクリプト: ${scriptPath}`);

    return { success: errors.length === 0, resources, manualSteps, errors };
  }

  async verify(client: DatadogClient): Promise<VerificationResult> {
    const checks = [];
    try {
      const resp = await client.v1.azure.listAzureIntegration();
      const found = resp.some((a) => a.tenantName === this.createdResources[0]?.id);
      checks.push({
        name: "Azure統合が登録されている",
        passed: found,
        detail: found ? undefined : "テナントが見つかりません",
      });
    } catch (err) {
      checks.push({
        name: "Azure統合の確認",
        passed: false,
        detail: err instanceof Error ? err.message : String(err),
      });
    }
    return { success: checks.every((c) => c.passed), checks };
  }
}

function generateAzSetupScript(config: AzureConfig): string {
  return `#!/bin/bash
# Datadog Azure Integration Setup (generated by Datadog Connect)
# Tenant: ${config.tenantName}

set -e

echo "=== Azure Datadog統合セットアップ ==="

# 1. App Registration 作成 (既存の場合はスキップ)
echo "1. App Registrationを確認中..."
APP_ID=${escapeShellArg(config.clientId)}

# 2. 各サブスクリプションにReaderロールを付与
echo "2. Readerロールを付与中..."
${config.subscriptionIds
  .map(
    (id) => `az role assignment create \\
  --assignee "\${APP_ID}" \\
  --role "Reader" \\
  --scope "/subscriptions/${escapeShellArg(id)}"`
  )
  .join("\n\n")}

echo ""
echo "=== セットアップ完了 ==="
echo "Datadogでの統合確認をしてください。"
`;
}

registerModule(new AzureModule());
