import { input, checkbox, confirm } from "@inquirer/prompts";
import { BaseModule } from "../base-module.js";
import { registerModule } from "../registry.js";
import { promptTags } from "../shared/tags.js";
import { printManual } from "../../utils/prompts.js";
import type { ModuleConfig, ExecutionResult, VerificationResult } from "../../config/types.js";
import type { DatadogClient } from "../../client/datadog-client.js";
import { writeExecutableFile, getSecureOutputDir } from "../../utils/secure-write.js";
import { escapeShellArg } from "../../utils/validators.js";

const GCP_SERVICES = [
  "compute", "cloud-sql", "gke", "cloud-functions", "pub-sub",
  "cloud-storage", "bigquery", "cloud-run", "memorystore",
  "cloud-composer", "dataflow", "filestore",
];

interface GcpConfig extends ModuleConfig {
  projectId: string;
  serviceAccountEmail: string;
  services: string[];
  enableLogs: boolean;
  enableCost: boolean;
  enableCspm: boolean;
  automute: boolean;
  tags: string[];
}

class GcpModule extends BaseModule {
  readonly id = "gcp";
  readonly name = "GCP統合";
  readonly description = "GCPプロジェクトとDatadogを接続";
  readonly category = "cloud" as const;
  readonly dependencies: string[] = [];

  async prompt(): Promise<GcpConfig> {
    const projectId = await input({
      message: "GCP Project ID:",
      validate: (v) => v.trim().length > 0 || "Project IDを入力してください",
    });

    const serviceAccountEmail = await input({
      message: "サービスアカウント Email (未作成の場合は空でOK):",
      default: `datadog-integration@${projectId}.iam.gserviceaccount.com`,
    });

    const services = await checkbox({
      message: "メトリクスを収集するGCPサービス:",
      choices: GCP_SERVICES.map((s) => ({
        value: s,
        name: s,
        checked: ["compute", "cloud-sql", "gke", "cloud-functions"].includes(s),
      })),
    });

    const enableLogs = await confirm({
      message: "Cloud Loggingエクスポートを有効にしますか？",
      default: true,
    });

    const enableCost = await confirm({
      message: "コスト管理を有効にしますか？",
      default: false,
    });

    const enableCspm = await confirm({
      message: "CSPM (クラウドセキュリティ態勢管理) を有効にしますか？",
      default: false,
    });

    const automute = await confirm({
      message: "GCEインスタンス停止時の自動ミュートを有効にしますか？",
      default: true,
    });

    const tags = await promptTags();

    return { projectId, serviceAccountEmail, services, enableLogs, enableCost, enableCspm, automute, tags };
  }

  async execute(config: GcpConfig, client: DatadogClient): Promise<ExecutionResult> {
    const resources = [];
    const manualSteps = [];
    const errors = [];

    try {
      await client.v2.gcp.createGCPSTSAccount({
        body: {
          data: {
            type: "gcp_service_account",
            attributes: {
              clientEmail: config.serviceAccountEmail,
              automute: config.automute,
            },
          },
        },
      });

      resources.push({
        type: "gcp_integration",
        id: config.projectId,
        name: `GCP Project ${config.projectId}`,
        createdAt: new Date().toISOString(),
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      errors.push(`GCP統合作成失敗: ${msg}`);
    }

    // Generate gcloud commands
    const gcloudCommands = generateGcloudCommands(config);
    const outputDir = getSecureOutputDir();
    const scriptPath = `${outputDir}/gcp-setup.sh`;
    writeExecutableFile(scriptPath, gcloudCommands);

    manualSteps.push({
      title: "GCPサービスアカウントを作成・設定",
      description: "以下のgcloudコマンドを実行してサービスアカウントを作成し、必要なロールを付与してください。",
      commands: [
        `chmod +x ${scriptPath}`,
        `./${scriptPath}`,
      ],
      outputFile: scriptPath,
    });

    printManual(`GCPセットアップスクリプト: ${scriptPath}`);

    return { success: errors.length === 0, resources, manualSteps, errors };
  }

  async verify(client: DatadogClient): Promise<VerificationResult> {
    const checks = [];
    try {
      const resp = await client.v2.gcp.listGCPSTSAccounts();
      const accounts = resp.data ?? [];
      const found = accounts.length > 0;
      checks.push({
        name: "GCP STS統合が登録されている",
        passed: found,
        detail: found ? `${accounts.length}件のアカウント` : "アカウントが見つかりません",
      });
    } catch (err) {
      checks.push({
        name: "GCP統合の確認",
        passed: false,
        detail: err instanceof Error ? err.message : String(err),
      });
    }
    return { success: checks.every((c) => c.passed), checks };
  }
}

function generateGcloudCommands(config: GcpConfig): string {
  const saName = config.serviceAccountEmail.split("@")[0];
  return `#!/bin/bash
# Datadog GCP Integration Setup (generated by Datadog Connect)
# Project: ${config.projectId}

set -e

PROJECT_ID=${escapeShellArg(config.projectId)}
SA_NAME=${escapeShellArg(saName)}
SA_EMAIL=${escapeShellArg(config.serviceAccountEmail)}

echo "=== GCP Datadog統合セットアップ ==="

# 1. サービスアカウント作成
echo "1. サービスアカウントを作成中..."
gcloud iam service-accounts create "\${SA_NAME}" \\
  --project="\${PROJECT_ID}" \\
  --display-name="Datadog Integration" \\
  --description="Service account for Datadog monitoring integration"

# 2. 必要なロールを付与
echo "2. ロールを付与中..."
ROLES=(
  "roles/compute.viewer"
  "roles/monitoring.viewer"
  "roles/cloudasset.viewer"
  "roles/browser"
)

for ROLE in "\${ROLES[@]}"; do
  gcloud projects add-iam-policy-binding "\${PROJECT_ID}" \\
    --member="serviceAccount:\${SA_EMAIL}" \\
    --role="\${ROLE}" \\
    --quiet
done

# 3. サービスアカウントキーを生成
echo "3. サービスアカウントキーを生成中..."
gcloud iam service-accounts keys create ./gcp-sa-key.json \\
  --iam-account="\${SA_EMAIL}" \\
  --project="\${PROJECT_ID}"

echo ""
echo "=== セットアップ完了 ==="
echo "サービスアカウントキー: ./gcp-sa-key.json"
echo "Datadogにアップロードしてください。"
`;
}

registerModule(new GcpModule());
