import { select, input, confirm } from "@inquirer/prompts";
import { BaseModule } from "../base-module.js";
import { registerModule } from "../registry.js";
import { printManual } from "../../utils/prompts.js";
import type { ModuleConfig, ExecutionResult, VerificationResult } from "../../config/types.js";
import type { DatadogClient } from "../../client/datadog-client.js";
import { writeSecureFile, getSecureOutputDir } from "../../utils/secure-write.js";

const K8S_DISTROS = [
  { value: "eks", name: "Amazon EKS" },
  { value: "gke", name: "Google GKE" },
  { value: "aks", name: "Azure AKS" },
  { value: "vanilla", name: "Vanilla Kubernetes" },
  { value: "openshift", name: "Red Hat OpenShift" },
  { value: "rancher", name: "Rancher" },
];

const INSTALL_METHODS = [
  { value: "helm", name: "Helm Chart (推奨)" },
  { value: "operator", name: "Datadog Operator" },
  { value: "daemonset", name: "DaemonSet Manifest" },
];

interface K8sConfig extends ModuleConfig {
  distro: string;
  installMethod: string;
  clusterName: string;
  enableApm: boolean;
  enableLogs: boolean;
  enableNpm: boolean;
  enableLiveProcesses: boolean;
  enableOrchestratorExplorer: boolean;
  enableAdmissionController: boolean;
}

class KubernetesModule extends BaseModule {
  readonly id = "kubernetes";
  readonly name = "Kubernetes";
  readonly description = "K8sクラスタにDatadog Agentをデプロイ";
  readonly category = "cloud" as const;
  readonly dependencies: string[] = [];

  async prompt(): Promise<K8sConfig> {
    const distro = await select({
      message: "Kubernetes ディストリビューション:",
      choices: K8S_DISTROS,
    });

    const installMethod = await select({
      message: "インストール方法:",
      choices: INSTALL_METHODS,
    });

    const clusterName = await input({
      message: "クラスタ名:",
      validate: (v) => v.trim().length > 0 || "クラスタ名を入力してください",
    });

    const enableApm = await confirm({ message: "APMを有効にしますか？", default: true });
    const enableLogs = await confirm({ message: "ログ収集を有効にしますか？", default: true });
    const enableNpm = await confirm({ message: "ネットワーク監視 (NPM) を有効にしますか？", default: false });
    const enableLiveProcesses = await confirm({ message: "Live Processesを有効にしますか？", default: true });
    const enableOrchestratorExplorer = await confirm({ message: "Orchestrator Explorerを有効にしますか？", default: true });
    const enableAdmissionController = await confirm({ message: "Admission Controller (自動計装) を有効にしますか？", default: true });

    return {
      distro, installMethod, clusterName,
      enableApm, enableLogs, enableNpm,
      enableLiveProcesses, enableOrchestratorExplorer, enableAdmissionController,
    };
  }

  async execute(config: K8sConfig): Promise<ExecutionResult> {
    const manualSteps = [];
    const outputDir = getSecureOutputDir();

    if (config.installMethod === "helm") {
      const values = generateHelmValues(config);
      const valuesPath = `${outputDir}/datadog-values.yaml`;
      writeSecureFile(valuesPath, values);

      manualSteps.push({
        title: "Helm Chart でDatadog Agentをデプロイ",
        description: "以下のコマンドでDatadog Agentをクラスタにデプロイしてください。",
        commands: [
          `helm repo add datadog https://helm.datadoghq.com`,
          `helm repo update`,
          `kubectl create secret generic datadog-secret \\`,
          `  --from-literal api-key=<YOUR_DD_API_KEY> \\`,
          `  --from-literal app-key=<YOUR_DD_APP_KEY>`,
          `helm install datadog-agent datadog/datadog \\`,
          `  -f ${valuesPath} \\`,
          `  --set datadog.apiKeyExistingSecret=datadog-secret \\`,
          `  --set datadog.appKeyExistingSecret=datadog-secret`,
        ],
        outputFile: valuesPath,
      });

      printManual(`Helm values: ${valuesPath}`);
    } else if (config.installMethod === "operator") {
      const cr = generateOperatorCR(config);
      const crPath = `${outputDir}/datadog-agent-cr.yaml`;
      writeSecureFile(crPath, cr);

      manualSteps.push({
        title: "Datadog Operatorでデプロイ",
        description: "Datadog Operatorをインストールし、DatadogAgent CRをapplyしてください。",
        commands: [
          `helm repo add datadog https://helm.datadoghq.com`,
          `helm install datadog-operator datadog/datadog-operator`,
          `kubectl apply -f ${crPath}`,
        ],
        outputFile: crPath,
      });

      printManual(`Operator CR: ${crPath}`);
    }

    return { success: true, resources: [], manualSteps, errors: [] };
  }

  async verify(_client: DatadogClient): Promise<VerificationResult> {
    return {
      success: true,
      checks: [{
        name: "K8s Agent デプロイ手順出力確認",
        passed: true,
        detail: "kubectl get pods -l app=datadog-agent でPodを確認してください",
      }],
    };
  }
}

function generateHelmValues(config: K8sConfig): string {
  return `# Datadog Helm Values (generated by Datadog Connect)
# Cluster: ${config.clusterName}
# Distro: ${config.distro}

datadog:
  clusterName: "${config.clusterName}"
  site: "datadoghq.com"  # wizard sets this

  # APM
  apm:
    portEnabled: ${config.enableApm}
    socketEnabled: ${config.enableApm}

  # Logs
  logs:
    enabled: ${config.enableLogs}
    containerCollectAll: ${config.enableLogs}

  # Network Performance Monitoring
  networkMonitoring:
    enabled: ${config.enableNpm}

  # Live Processes
  processAgent:
    enabled: ${config.enableLiveProcesses}
    processCollection: ${config.enableLiveProcesses}

  # Orchestrator Explorer
  orchestratorExplorer:
    enabled: ${config.enableOrchestratorExplorer}

clusterAgent:
  enabled: true
  replicas: 2
  ${config.enableAdmissionController ? `admissionController:
    enabled: true
    mutateUnlabelled: false` : ""}

${config.distro === "openshift" ? `agents:
  tolerations:
    - operator: Exists
  podSecurity:
    seLinuxContext:
      seLinuxOptions:
        user: system_u
        role: system_r
        type: spc_t
        level: s0` : ""}
`;
}

function generateOperatorCR(config: K8sConfig): string {
  return `# DatadogAgent Custom Resource (generated by Datadog Connect)
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: "${config.clusterName}"
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
  features:
    apm:
      enabled: ${config.enableApm}
    logCollection:
      enabled: ${config.enableLogs}
      containerCollectAll: ${config.enableLogs}
    npm:
      enabled: ${config.enableNpm}
    liveProcessCollection:
      enabled: ${config.enableLiveProcesses}
    orchestratorExplorer:
      enabled: ${config.enableOrchestratorExplorer}
    admissionController:
      enabled: ${config.enableAdmissionController}
`;
}

registerModule(new KubernetesModule());
