/**
 * cloud-configs.ts
 *
 * Pure data exports for all cloud integration knowledge extracted from the
 * cloud modules (aws, gcp, azure, kubernetes, on-prem, xserver).
 * No imports from @datadog/ or DatadogClient — fully self-contained.
 */

// ─────────────────────────────────────────────
// AWS
// ─────────────────────────────────────────────

/** All AWS services supported for metric collection */
export const AWS_SERVICES = [
  "ec2",
  "rds",
  "elb",
  "elbv2",
  "lambda",
  "s3",
  "cloudfront",
  "dynamodb",
  "ecs",
  "eks",
  "elasticache",
  "kinesis",
  "sqs",
  "sns",
  "redshift",
  "apigateway",
  "route53",
] as const;

export type AwsService = (typeof AWS_SERVICES)[number];

/** AWS services enabled for metric collection by default */
export const AWS_DEFAULT_SERVICES: AwsService[] = [
  "ec2",
  "rds",
  "elb",
  "lambda",
  "s3",
];

/** AWS log sources available for collection */
export const AWS_LOG_SERVICES = [
  "cloudtrail",
  "vpc-flow-logs",
  "rds",
  "lambda",
  "elb",
  "s3-access",
  "cloudfront",
] as const;

export type AwsLogService = (typeof AWS_LOG_SERVICES)[number];

/** AWS log sources enabled by default */
export const AWS_DEFAULT_LOG_SERVICES: AwsLogService[] = [
  "cloudtrail",
  "vpc-flow-logs",
];

/** AWS regions available for selection, with default selections */
export const AWS_REGIONS = [
  { value: "ap-northeast-1", name: "ap-northeast-1 (Tokyo)", defaultChecked: true },
  { value: "us-east-1", name: "us-east-1 (N. Virginia)", defaultChecked: true },
  { value: "us-west-2", name: "us-west-2 (Oregon)", defaultChecked: false },
  { value: "eu-west-1", name: "eu-west-1 (Ireland)", defaultChecked: false },
  { value: "ap-southeast-1", name: "ap-southeast-1 (Singapore)", defaultChecked: false },
] as const;

/**
 * IAM role name suffix used by the AWS integration.
 * Combined with RESOURCE_PREFIX: `${RESOURCE_PREFIX}-DatadogIntegrationRole`
 */
export const AWS_IAM_ROLE_NAME_SUFFIX = "DatadogIntegrationRole" as const;

/** Datadog AWS account principal for cross-account trust */
export const AWS_DATADOG_PRINCIPAL_ARN = "arn:aws:iam::464622532012:root" as const;

/**
 * Generates a CloudFormation template that creates the Datadog Integration IAM role.
 * @param resourcePrefix - The RESOURCE_PREFIX constant value (e.g. "DD-Connect")
 */
export function generateAwsCfnTemplate(resourcePrefix: string): string {
  return `AWSTemplateFormatVersion: '2010-09-09'
Description: Datadog Integration IAM Role (generated by Datadog Connect)

Parameters:
  ExternalId:
    Type: String
    Description: External ID from Datadog (AWS Integration page > Account Details > AWS External ID)
    # IMPORTANT: Replace this with your actual Datadog External ID
    # Find it at: Datadog > Integrations > Amazon Web Services > Add AWS Account > AWS External ID
    Default: '<YOUR_DATADOG_EXTERNAL_ID>'

Resources:
  DatadogIntegrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${resourcePrefix}-DatadogIntegrationRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: '${AWS_DATADOG_PRINCIPAL_ARN}'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/SecurityAudit'
      Policies:
        - PolicyName: DatadogAWSIntegrationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'apigateway:GET'
                  - 'autoscaling:Describe*'
                  - 'backup:List*'
                  - 'budgets:ViewBudget'
                  - 'cloudfront:GetDistributionConfig'
                  - 'cloudfront:ListDistributions'
                  - 'cloudtrail:DescribeTrails'
                  - 'cloudtrail:GetTrailStatus'
                  - 'cloudtrail:LookupEvents'
                  - 'cloudwatch:Describe*'
                  - 'cloudwatch:Get*'
                  - 'cloudwatch:List*'
                  - 'codedeploy:List*'
                  - 'codedeploy:BatchGet*'
                  - 'directconnect:Describe*'
                  - 'dynamodb:List*'
                  - 'dynamodb:Describe*'
                  - 'ec2:Describe*'
                  - 'ecs:Describe*'
                  - 'ecs:List*'
                  - 'elasticache:Describe*'
                  - 'elasticache:List*'
                  - 'elasticfilesystem:DescribeFileSystems'
                  - 'elasticfilesystem:DescribeTags'
                  - 'elasticloadbalancing:Describe*'
                  - 'elasticmapreduce:List*'
                  - 'elasticmapreduce:Describe*'
                  - 'es:DescribeElasticsearchDomains'
                  - 'es:ListDomainNames'
                  - 'es:ListTags'
                  - 'health:DescribeEvents'
                  - 'health:DescribeEventDetails'
                  - 'health:DescribeAffectedEntities'
                  - 'kinesis:List*'
                  - 'kinesis:Describe*'
                  - 'lambda:GetPolicy'
                  - 'lambda:List*'
                  - 'logs:DeleteSubscriptionFilter'
                  - 'logs:DescribeLogGroups'
                  - 'logs:DescribeLogStreams'
                  - 'logs:DescribeSubscriptionFilters'
                  - 'logs:FilterLogEvents'
                  - 'logs:PutSubscriptionFilter'
                  - 'logs:TestMetricFilter'
                  - 'rds:Describe*'
                  - 'rds:List*'
                  - 'redshift:DescribeClusters'
                  - 'redshift:DescribeLoggingStatus'
                  - 'route53:List*'
                  - 's3:GetBucketLogging'
                  - 's3:GetBucketLocation'
                  - 's3:GetBucketNotification'
                  - 's3:GetBucketTagging'
                  - 's3:ListAllMyBuckets'
                  - 's3:PutBucketNotification'
                  - 'ses:Get*'
                  - 'sns:List*'
                  - 'sns:Publish'
                  - 'sqs:ListQueues'
                  - 'states:ListStateMachines'
                  - 'states:DescribeStateMachine'
                  - 'support:DescribeTrustedAdvisor*'
                  - 'support:RefreshTrustedAdvisorCheck'
                  - 'tag:GetResources'
                  - 'tag:GetTagKeys'
                  - 'tag:GetTagValues'
                  - 'xray:BatchGetTraces'
                  - 'xray:GetTraceSummaries'
                Resource: '*'

Outputs:
  RoleArn:
    Description: The ARN of the Datadog Integration IAM Role
    Value: !GetAtt DatadogIntegrationRole.Arn
`;
}

// ─────────────────────────────────────────────
// GCP
// ─────────────────────────────────────────────

/** Default GCP service account email pattern */
export const GCP_DEFAULT_SA_EMAIL_PATTERN =
  "datadog-integration@{projectId}.iam.gserviceaccount.com" as const;

/** GCP IAM roles required for Datadog integration */
export const GCP_REQUIRED_ROLES = [
  "roles/compute.viewer",
  "roles/monitoring.viewer",
  "roles/cloudasset.viewer",
  "roles/browser",
] as const;

/** Service account name validation pattern (GCP naming rules) */
export const GCP_SA_EMAIL_PATTERN =
  /^[a-z][a-z0-9-]{4,28}[a-z0-9]@[a-z][a-z0-9-]{4,28}[a-z0-9]\.iam\.gserviceaccount\.com$/;

/**
 * Generates a bash script for setting up the GCP service account and
 * configuring Workload Identity Federation (keyless authentication).
 */
export function generateGcpSetupScript(
  projectId: string,
  serviceAccountEmail: string,
  automute: boolean,
  tags: string[]
): string {
  const saName = serviceAccountEmail.split("@")[0];
  const escapedProjectId = shellEscape(projectId);
  const escapedSaName = shellEscape(saName);
  const escapedSaEmail = shellEscape(serviceAccountEmail);

  return `#!/bin/bash
# Datadog GCP Integration Setup (generated by Datadog Connect)
# Project: ${projectId}
${automute ? "# GCE automute: enabled" : ""}
${tags.length > 0 ? `# Host filters: ${tags.join(",")}` : ""}

set -e

PROJECT_ID=${escapedProjectId}
SA_NAME=${escapedSaName}
SA_EMAIL=${escapedSaEmail}

echo "=== GCP Datadog統合セットアップ ==="

# 1. サービスアカウント作成
echo "1. サービスアカウントを作成中..."
gcloud iam service-accounts create "\${SA_NAME}" \\
  --project="\${PROJECT_ID}" \\
  --display-name="Datadog Integration" \\
  --description="Service account for Datadog monitoring integration"

# 2. 必要なロールを付与
echo "2. ロールを付与中..."
ROLES=(
  "roles/compute.viewer"
  "roles/monitoring.viewer"
  "roles/cloudasset.viewer"
  "roles/browser"
)

for ROLE in "\${ROLES[@]}"; do
  gcloud projects add-iam-policy-binding "\${PROJECT_ID}" \\
    --member="serviceAccount:\${SA_EMAIL}" \\
    --role="\${ROLE}" \\
    --quiet
done

# 3. Workload Identity Federation (WIF) を設定
echo "3. Workload Identity Federation を設定中..."
echo ""
echo "Datadog の STS 統合はキーレス認証（Workload Identity Federation）を使用します。"
echo "サービスアカウントキーの生成は不要です。"
echo ""
echo "--- WIF 設定手順 ---"
echo "1. Datadog コンソールで GCP 統合ページを開く:"
echo "   https://app.datadoghq.com/integrations/google-cloud-platform"
echo ""
echo "2. 'Add GCP Account' → 'Service Account Impersonation' を選択"
echo ""
echo "3. 表示される Datadog の Workload Identity Pool 情報をコピー:"
echo "   - Pool Provider: (Datadog コンソールに表示される値)"
echo "   - Service Account: (上で作成した \${SA_EMAIL})"
echo ""
echo "4. GCP 側で WIF を設定:"
gcloud iam service-accounts add-iam-policy-binding "\${SA_EMAIL}" \\
  --project="\${PROJECT_ID}" \\
  --role="roles/iam.workloadIdentityUser" \\
  --member="principalSet://iam.googleapis.com/projects/\${PROJECT_ID}/locations/global/workloadIdentityPools/datadog-pool/*" \\
  --quiet 2>/dev/null || echo "   WIF バインディングは Datadog コンソールの Pool 情報確定後に手動で実行してください。"
echo ""
echo "=== セットアップ完了 ==="
echo "Datadog コンソール (https://app.datadoghq.com/integrations/google-cloud-platform) で"
echo "GCP 統合の設定を確認してください。"
`;
}

// ─────────────────────────────────────────────
// Azure
// ─────────────────────────────────────────────

/** Azure IAM role required for Datadog integration on each subscription */
export const AZURE_REQUIRED_ROLE = "Reader" as const;

/** Datadog console URL for Azure integration */
export const AZURE_INTEGRATION_CONSOLE_URL =
  "https://app.datadoghq.com/integrations/azure" as const;

/**
 * Generates an az CLI bash script that assigns the Reader role to the
 * App Registration service principal on each subscription.
 */
export function generateAzureSetupScript(
  tenantName: string,
  clientId: string,
  subscriptionIds: string[]
): string {
  const escapedClientId = shellEscape(clientId);
  const roleAssignments = subscriptionIds
    .map(
      (id) =>
        `az role assignment create \\\n  --assignee "\${APP_ID}" \\\n  --role "Reader" \\\n  --scope "/subscriptions/${shellEscape(id)}"`
    )
    .join("\n\n");

  return `#!/bin/bash
# Datadog Azure Integration Setup (generated by Datadog Connect)
# Tenant: ${tenantName}

set -e

echo "=== Azure Datadog統合セットアップ ==="

# 1. App Registration 作成 (既存の場合はスキップ)
echo "1. App Registrationを確認中..."
APP_ID=${escapedClientId}

# 2. 各サブスクリプションにReaderロールを付与
echo "2. Readerロールを付与中..."
${roleAssignments}

echo ""
echo "=== セットアップ完了 ==="
echo "Datadogでの統合確認をしてください。"
`;
}

// ─────────────────────────────────────────────
// Kubernetes
// ─────────────────────────────────────────────

export interface K8sDistro {
  value: string;
  name: string;
}

export interface K8sInstallMethod {
  value: string;
  name: string;
}

/** Supported Kubernetes distributions */
export const K8S_DISTROS: readonly K8sDistro[] = [
  { value: "eks", name: "Amazon EKS" },
  { value: "gke", name: "Google GKE" },
  { value: "aks", name: "Azure AKS" },
  { value: "vanilla", name: "Vanilla Kubernetes" },
  { value: "openshift", name: "Red Hat OpenShift" },
  { value: "rancher", name: "Rancher" },
] as const;

/** Agent installation methods for Kubernetes */
export const K8S_INSTALL_METHODS: readonly K8sInstallMethod[] = [
  { value: "helm", name: "Helm Chart (推奨)" },
  { value: "operator", name: "Datadog Operator" },
  { value: "daemonset", name: "DaemonSet Manifest" },
] as const;

export interface K8sFeatureFlags {
  enableApm: boolean;
  enableLogs: boolean;
  enableNpm: boolean;
  enableLiveProcesses: boolean;
  enableOrchestratorExplorer: boolean;
  enableAdmissionController: boolean;
}

/**
 * Generates a Helm values.yaml for deploying the Datadog Agent.
 * Uses datadog/datadog chart with cluster agent enabled (2 replicas).
 */
export function generateK8sHelmValues(
  clusterName: string,
  distro: string,
  flags: K8sFeatureFlags
): string {
  return `# Datadog Helm Values (generated by Datadog Connect)
# Cluster: ${clusterName}
# Distro: ${distro}

datadog:
  clusterName: "${clusterName}"
  site: "datadoghq.com"  # wizard sets this

  # APM
  apm:
    portEnabled: ${flags.enableApm}
    socketEnabled: ${flags.enableApm}

  # Logs
  logs:
    enabled: ${flags.enableLogs}
    containerCollectAll: ${flags.enableLogs}

  # Network Performance Monitoring
  networkMonitoring:
    enabled: ${flags.enableNpm}

  # Live Processes
  processAgent:
    enabled: ${flags.enableLiveProcesses}
    processCollection: ${flags.enableLiveProcesses}

  # Orchestrator Explorer
  orchestratorExplorer:
    enabled: ${flags.enableOrchestratorExplorer}

clusterAgent:
  enabled: true
  replicas: 2
  ${
    flags.enableAdmissionController
      ? `admissionController:
    enabled: true
    mutateUnlabelled: false`
      : ""
  }

${
  distro === "openshift"
    ? `agents:
  tolerations:
    - operator: Exists
  podSecurity:
    seLinuxContext:
      seLinuxOptions:
        user: system_u
        role: system_r
        type: spc_t
        level: s0`
    : ""
}
`;
}

/**
 * Generates a DatadogAgent Custom Resource manifest for the Datadog Operator.
 * Uses datadoghq.com/v2alpha1 API version.
 */
export function generateK8sOperatorCR(
  clusterName: string,
  flags: K8sFeatureFlags
): string {
  return `# DatadogAgent Custom Resource (generated by Datadog Connect)
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: "${clusterName}"
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
  features:
    apm:
      enabled: ${flags.enableApm}
    logCollection:
      enabled: ${flags.enableLogs}
      containerCollectAll: ${flags.enableLogs}
    npm:
      enabled: ${flags.enableNpm}
    liveProcessCollection:
      enabled: ${flags.enableLiveProcesses}
    orchestratorExplorer:
      enabled: ${flags.enableOrchestratorExplorer}
    admissionController:
      enabled: ${flags.enableAdmissionController}
`;
}

/** Helm repository URL for Datadog charts */
export const K8S_HELM_REPO_URL = "https://helm.datadoghq.com" as const;

/** Helm chart name for Datadog Agent */
export const K8S_HELM_CHART = "datadog/datadog" as const;

/** Helm chart name for Datadog Operator */
export const K8S_OPERATOR_HELM_CHART = "datadog/datadog-operator" as const;

// ─────────────────────────────────────────────
// On-Premises
// ─────────────────────────────────────────────

export interface OsOption {
  value: string;
  name: string;
}

export interface CmToolOption {
  value: string;
  name: string;
}

/** Supported operating systems for on-premises Agent installation */
export const ON_PREM_OS_OPTIONS: readonly OsOption[] = [
  { value: "ubuntu", name: "Ubuntu / Debian" },
  { value: "centos", name: "CentOS / RHEL / Amazon Linux" },
  { value: "suse", name: "SUSE Linux" },
  { value: "macos", name: "macOS" },
  { value: "windows", name: "Windows" },
] as const;

/** Supported configuration management tools */
export const ON_PREM_CM_TOOLS: readonly CmToolOption[] = [
  { value: "none", name: "なし (手動)" },
  { value: "ansible", name: "Ansible" },
  { value: "chef", name: "Chef" },
  { value: "puppet", name: "Puppet" },
] as const;

/** URL for the Datadog Agent 7 Linux install script */
export const AGENT_INSTALL_SCRIPT_URL =
  "https://s3.amazonaws.com/dd-agent/scripts/install_script_agent7.sh" as const;

/** URL for the Datadog Agent 7 Windows install script */
export const AGENT_INSTALL_SCRIPT_WINDOWS_URL =
  "https://s3.amazonaws.com/dd-agent/scripts/install_script_agent7.ps1" as const;

export interface OnPremFeatureFlags {
  enableProcess: boolean;
  enableNetwork: boolean;
  enableContainer: boolean;
}

/**
 * Generates the Agent installation bash script for Linux/macOS.
 * For Windows, use generateWindowsInstallScript() instead.
 */
export function generateLinuxInstallScript(
  os: string,
  tags: string[],
  flags: OnPremFeatureFlags
): string {
  const tagStr = tags.length > 0 ? tags.join(",") : "";
  const tagLine = tagStr ? `DD_HOST_TAGS=${shellEscape(tagStr)}` : "";

  return `#!/bin/bash
# Datadog Agent Install - ${os}
# Generated by Datadog Connect

set -e

DD_API_KEY="<YOUR_DD_API_KEY>"
${tagLine}

echo "=== Datadog Agent インストール ==="

DD_AGENT_MAJOR_VERSION=7 DD_API_KEY="\${DD_API_KEY}" \\
  ${tagLine ? `DD_HOST_TAGS="\${DD_HOST_TAGS}" \\` : ""}
  bash -c "$(curl -L ${AGENT_INSTALL_SCRIPT_URL})"

${
  flags.enableProcess
    ? `# プロセス監視有効化
echo "process_config:" >> /etc/datadog-agent/datadog.yaml
echo "  process_collection:" >> /etc/datadog-agent/datadog.yaml
echo "    enabled: true" >> /etc/datadog-agent/datadog.yaml`
    : ""
}

${
  flags.enableNetwork
    ? `# ネットワーク監視有効化
echo "network_config:" >> /etc/datadog-agent/system-probe.yaml
echo "  enabled: true" >> /etc/datadog-agent/system-probe.yaml`
    : ""
}

# Agent再起動
systemctl restart datadog-agent

echo "=== インストール完了 ==="
datadog-agent status | head -20
`;
}

/**
 * Escapes special characters for safe interpolation inside PowerShell double-quoted strings.
 * Escapes backtick, double-quote, and dollar sign.
 */
function escapePowerShell(s: string): string {
  return s.replace(/[`"$]/g, '`$&');
}

/**
 * Generates the Agent installation PowerShell script for Windows.
 */
export function generateWindowsInstallScript(tags: string[]): string {
  const tagList = tags.map(escapePowerShell).join(",");
  return `# Datadog Agent Install - Windows
# Run in PowerShell as Administrator

$env:DD_API_KEY = "<YOUR_DD_API_KEY>"
${tagList ? `$env:DD_HOST_TAGS = "${tagList}"` : ""}

. { Set-ExecutionPolicy Bypass -Scope Process; [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString('${AGENT_INSTALL_SCRIPT_WINDOWS_URL}')) }
`;
}

/**
 * Generates a datadog.yaml config snippet for on-premises hosts.
 * Append to /etc/datadog-agent/datadog.yaml.
 */
export function generateAgentConfigSnippet(
  tags: string[],
  flags: OnPremFeatureFlags
): string {
  return `# Datadog Agent Configuration Snippet
# Add to /etc/datadog-agent/datadog.yaml

${tags.length > 0 ? `tags:\n${tags.map((t) => `  - "${t.replace(/"/g, '\\"')}"`).join("\n")}` : ""}

${
  flags.enableProcess
    ? `process_config:
  process_collection:
    enabled: true`
    : ""
}

${flags.enableContainer ? "container_collect_all: true" : ""}

logs_enabled: true
`;
}

/**
 * Generates an Ansible playbook for deploying the Datadog Agent.
 * Uses the datadog.datadog Ansible role.
 */
export function generateAnsiblePlaybook(tags: string[], flags: OnPremFeatureFlags): string {
  return `---
# Ansible Playbook - Datadog Agent
# Generated by Datadog Connect

- hosts: all
  become: true
  roles:
    - role: datadog.datadog
      datadog_api_key: "{{ datadog_api_key }}"
      datadog_agent_major_version: 7
      datadog_config:
        tags:
${tags.map((t) => `          - "${t}"`).join("\n")}
        process_config:
          process_collection:
            enabled: ${flags.enableProcess}
        logs_enabled: true
`;
}

// ─────────────────────────────────────────────
// Xserver VPS / Dedicated Server
// ─────────────────────────────────────────────

export interface XserverType {
  value: string;
  name: string;
}

/** Supported Xserver plan types */
export const XSERVER_TYPES: readonly XserverType[] = [
  { value: "vps", name: "Xserver VPS" },
  { value: "dedicated", name: "Xserver 専用サーバー" },
  { value: "business", name: "Xserver Business (SSH可)" },
] as const;

/** Outbound ports/destinations that must be allowed in Xserver firewall */
export const XSERVER_FIREWALL_RULES = [
  { protocol: "TCP", port: 443, destination: "*.datadoghq.com", description: "Datadog HTTPS" },
  { protocol: "TCP", port: 443, destination: "*.logs.datadoghq.com", description: "Datadog Logs HTTPS" },
] as const;

export interface XserverFeatureFlags {
  enableProcess: boolean;
  enableNginx: boolean;
  enableMysql: boolean;
}

/**
 * Generates the Datadog Agent install bash script for Xserver VPS/dedicated servers.
 */
export function generateXserverInstallScript(
  serverType: string,
  host: string,
  tags: string[],
  flags: XserverFeatureFlags
): string {
  const tagStr = tags.length > 0 ? tags.join(",") : "";

  return `#!/bin/bash
# Datadog Agent Install for Xserver (${serverType})
# Host: ${host}
# Generated by Datadog Connect

set -e

DD_API_KEY="<YOUR_DD_API_KEY>"

echo "=== Xserver Datadog Agent インストール ==="
echo "ホスト: ${shellEscape(host)}"
echo "タイプ: ${shellEscape(serverType)}"

# 1. Agent インストール
echo "1. Datadog Agent をインストール中..."
DD_AGENT_MAJOR_VERSION=7 DD_API_KEY="\${DD_API_KEY}" \\
  ${tagStr ? `DD_HOST_TAGS="${shellEscape(tagStr)}" \\` : ""}
  bash -c "$(curl -L ${AGENT_INSTALL_SCRIPT_URL})"

# 2. 追加設定
${
  flags.enableProcess
    ? `echo "2. プロセス監視を有効化..."
cat >> /etc/datadog-agent/datadog.yaml << 'EOF'

process_config:
  process_collection:
    enabled: true
EOF`
    : ""
}

# 3. Agent 再起動
echo "3. Agent を再起動中..."
systemctl restart datadog-agent

# 4. ステータス確認
echo ""
echo "=== インストール完了 ==="
datadog-agent status 2>/dev/null | head -30 || echo "Agent起動待ち..."

echo ""
echo "Datadog UIでホスト「$(hostname)」が表示されることを確認してください。"
`;
}

/**
 * Nginx integration config for the Datadog Agent.
 * Place at /etc/datadog-agent/conf.d/nginx.d/conf.yaml
 * Requires stub_status enabled in Nginx config.
 */
export const XSERVER_NGINX_CONFIG = `# Nginx Datadog Integration
# Place at: /etc/datadog-agent/conf.d/nginx.d/conf.yaml

init_config:

instances:
  - nginx_status_url: http://localhost/nginx_status
    tags:
      - managed:datadog-connect

# Nginx側でstub_statusを有効にする必要があります:
# server {
#   listen 80;
#   server_name localhost;
#   location /nginx_status {
#     stub_status on;
#     allow 127.0.0.1;
#     deny all;
#   }
# }
` as const;

/**
 * MySQL/MariaDB integration config for the Datadog Agent.
 * Place at /etc/datadog-agent/conf.d/mysql.d/conf.yaml
 * Requires a dedicated 'datadog' MySQL user with appropriate grants.
 */
export const XSERVER_MYSQL_CONFIG = `# MySQL Datadog Integration
# Place at: /etc/datadog-agent/conf.d/mysql.d/conf.yaml

init_config:

instances:
  - host: 127.0.0.1
    username: datadog
    password: "<DATADOG_USER_PASSWORD>"
    port: 3306
    options:
      replication: false
      galera_cluster: false
      extra_status_metrics: true
      extra_innodb_metrics: true
      schema_size_metrics: true
    tags:
      - managed:datadog-connect
` as const;

/** MySQL grants required for the Datadog monitoring user */
export const XSERVER_MYSQL_GRANTS = [
  "GRANT REPLICATION CLIENT, PROCESS ON *.* TO 'datadog'@'localhost';",
  "GRANT SELECT ON performance_schema.* TO 'datadog'@'localhost';",
] as const;

// ─────────────────────────────────────────────
// Shared utility
// ─────────────────────────────────────────────

/**
 * Escapes a string for safe use in single-quoted shell arguments.
 * Wraps value in single quotes and escapes embedded single quotes.
 * Internal helper — mirrors escapeShellArg in validators.ts.
 */
function shellEscape(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}
