/**
 * security-rules.ts
 *
 * Pure data exports for all security-domain knowledge extracted from the
 * security modules (cspm, cws, asm, siem, sensitiveData).
 * No imports from @datadog/ or DatadogClient — fully self-contained.
 */

// ─────────────────────────────────────────────
// Shared local types
// ─────────────────────────────────────────────

export type CloudProvider = "aws" | "gcp" | "azure";
export type ScanTarget = "vulnHostOs" | "vulnContainersOs" | "lambda";
export type ProtectionTarget = "file_integrity" | "process_exec" | "network_conn";
export type PresetPolicy = "web_server" | "database" | "container_runtime";
export type WafTarget = "sqli" | "xss" | "cmdi" | "path_traversal";
export type SensitiveDataPattern = "pii" | "credit-card" | "api-key" | "email" | "phone";
export type SiemPack = "cloud" | "auth" | "network" | "app";
export type SiemRuleStatus = "high" | "medium";
export type SiemAggregation = "count";

// ─────────────────────────────────────────────
// CSPM — Cloud Security Posture Management
// ─────────────────────────────────────────────

export interface CspmCloudProviderDef {
  value: CloudProvider;
  name: string;
}

export interface CspmScanTargetDef {
  value: ScanTarget;
  name: string;
  /** Whether the target is selected by default */
  defaultChecked: boolean;
}

/** Supported cloud providers for Agentless scanning */
export const CSPM_CLOUD_PROVIDERS: readonly CspmCloudProviderDef[] = [
  { value: "aws", name: "AWS" },
  { value: "gcp", name: "GCP" },
  { value: "azure", name: "Azure" },
] as const;

/** Scan target options for CSPM Agentless scanning */
export const CSPM_SCAN_TARGETS: readonly CspmScanTargetDef[] = [
  { value: "vulnHostOs", name: "ホスト脆弱性スキャン", defaultChecked: true },
  { value: "vulnContainersOs", name: "コンテナ脆弱性スキャン", defaultChecked: true },
  { value: "lambda", name: "Lambda脆弱性スキャン (AWS のみ)", defaultChecked: false },
] as const;

export interface CspmScanOptionsBase {
  vulnHostOs: boolean;
  vulnContainersOs: boolean;
}

export interface CspmAwsScanOptions extends CspmScanOptionsBase {
  lambda: boolean;
  /** Sensitive data scanning (disabled by default) */
  sensitiveData: boolean;
}

export interface CspmGcpScanOptions extends CspmScanOptionsBase {}

export interface CspmAzureScanOptions extends CspmScanOptionsBase {}

/** Default scan options when all targets are selected */
export const CSPM_DEFAULT_SCAN_OPTIONS: CspmAwsScanOptions = {
  vulnHostOs: true,
  vulnContainersOs: true,
  lambda: false,
  sensitiveData: false,
};

/** Datadog API resource types for CSPM */
export const CSPM_RESOURCE_TYPES = {
  aws: "aws_scan_options",
  gcp: "gcp_scan_options",
  azure: "azure_scan_options",
} as const;

// ─────────────────────────────────────────────
// CWS — Cloud Workload Security
// ─────────────────────────────────────────────

export interface CwsProtectionTargetDef {
  value: ProtectionTarget;
  name: string;
}

export interface CwsPresetPolicyDef {
  value: PresetPolicy;
  name: string;
}

/** Workload protection monitoring targets */
export const CWS_PROTECTION_TARGETS: readonly CwsProtectionTargetDef[] = [
  { value: "file_integrity", name: "ファイル改竄検知" },
  { value: "process_exec", name: "プロセス実行監視" },
  { value: "network_conn", name: "ネットワーク接続監視" },
] as const;

/** Built-in preset policies for common workload types */
export const CWS_PRESET_POLICIES: readonly CwsPresetPolicyDef[] = [
  { value: "web_server", name: "Web Server" },
  { value: "database", name: "Database" },
  { value: "container_runtime", name: "Container Runtime" },
] as const;

/**
 * system-probe.yaml template for enabling CWS on a host.
 * Place at /etc/datadog-agent/system-probe.yaml and restart the Agent.
 */
export function generateCwsSystemProbeYaml(targets: ProtectionTarget[]): string {
  const fileIntegrity = targets.includes("file_integrity");
  const processExec = targets.includes("process_exec");
  const networkConn = targets.includes("network_conn");

  return `# system-probe.yaml — CWS (Cloud Workload Security) 設定
# Generated by datadog-connect
# このファイルを /etc/datadog-agent/system-probe.yaml に配置し、
# Datadog Agent を再起動してください。

runtime_security_config:
  ## CWS 全体の有効化
  enabled: true

  ## ファイル改竄検知
  fim_enabled: ${fileIntegrity}

  ## プロセス実行監視
  ## process_exec は runtime_security_config.enabled=true で自動有効
  # process_exec_enabled: ${processExec}

  ## ネットワーク接続監視
  network:
    enabled: ${networkConn}

  ## ポリシーファイルの配置先 (オプション)
  # policies_dir: /etc/datadog-agent/runtime-security.d/

  ## イベントサーバー設定
  socket: /opt/datadog-agent/run/runtime-security.sock
`;
}

// ─────────────────────────────────────────────
// ASM — Application Security Management (WAF)
// ─────────────────────────────────────────────

export interface WafRuleDef {
  /** Display name for the rule */
  name: string;
  /** Attack category tag (e.g. "injection", "xss", "lfi") */
  category: string;
  /** DDWaf input address */
  conditionInput: string;
  /** DDWaf operator */
  conditionOperator: string;
  /** Regex pattern used to detect the attack */
  conditionValue: string;
}

/**
 * WAF custom rule definitions for ASM.
 * All rules are created in monitor mode (blocking: false) by default.
 * Enable blocking via the Datadog console after validation.
 */
export const ASM_WAF_RULES: Record<WafTarget, WafRuleDef> = {
  sqli: {
    name: "SQLi Detection",
    category: "injection",
    conditionInput: "server.request.query",
    conditionOperator: "match_regex",
    conditionValue:
      "(?i)(union|select|insert|drop|delete|update|exec|cast|convert|char|varchar|nchar|nvarchar|alter|begin|end|fetch|declare|open|cursor|kill|--)",
  },
  xss: {
    name: "XSS Detection",
    category: "xss",
    conditionInput: "server.request.query",
    conditionOperator: "match_regex",
    conditionValue: "(?i)(<script|javascript:|on\\w+=|<iframe|<object|<embed|<link|<meta)",
  },
  cmdi: {
    name: "Command Injection Detection",
    category: "injection",
    conditionInput: "server.request.query",
    conditionOperator: "match_regex",
    conditionValue:
      "(?i)(\\||;|&&|\\$\\(|`|\\bexec\\b|\\bsystem\\b|\\bpassthru\\b|\\bpopen\\b)",
  },
  path_traversal: {
    name: "Path Traversal Detection",
    category: "lfi",
    conditionInput: "server.request.query",
    conditionOperator: "match_regex",
    conditionValue: "(?i)(\\.\\./|\\.\\.\\\\/|%2e%2e%2f|%252e%252e%252f)",
  },
} as const;

export interface AsmProtectionTargetDef {
  value: WafTarget;
  name: string;
}

/** WAF protection targets presented to users */
export const ASM_PROTECTION_TARGETS: readonly AsmProtectionTargetDef[] = [
  { value: "sqli", name: "SQLi検出" },
  { value: "xss", name: "XSS検出" },
  { value: "cmdi", name: "コマンドインジェクション検出" },
  { value: "path_traversal", name: "パストラバーサル検出" },
] as const;

/** Default excluded paths for WAF exclusion filters */
export const ASM_DEFAULT_EXCLUDED_PATHS = ["/health", "/metrics"] as const;

/**
 * Setup instruction text for enabling DD_APPSEC_ENABLED in various environments.
 * ASM starts in monitor mode; enable blocking from the Datadog console.
 */
export function generateAsmAppsecSetup(excludedPaths: string[]): string {
  const excludeSection =
    excludedPaths.length > 0
      ? `\n# 除外パス (設定済み WAF 除外フィルター)\n${excludedPaths.map((p) => `# - ${p}`).join("\n")}\n`
      : "";

  return `# ASM (Application Security Management) 有効化手順
# Generated by datadog-connect

## 概要
ASM は monitor モード（検出のみ）で設定されています。
攻撃を検知しますが、ブロックは行いません。

## 1. 環境変数で有効化する場合

export DD_APPSEC_ENABLED=true

## 2. datadog.yaml で有効化する場合

appsec_enabled: true
${excludeSection}
## 3. Docker / Kubernetes での設定

### Docker
docker run -e DD_APPSEC_ENABLED=true ...

### Kubernetes (環境変数)
env:
  - name: DD_APPSEC_ENABLED
    value: "true"

## 4. 言語別 APM ライブラリの設定

### Node.js (dd-trace)
DD_APPSEC_ENABLED=true node -r dd-trace/init app.js

### Python (ddtrace)
DD_APPSEC_ENABLED=true ddtrace-run python app.py

### Java
java -javaagent:/opt/datadog/dd-java-agent.jar \\
  -Ddd.appsec.enabled=true \\
  -jar app.jar

### Go / Ruby / PHP
# https://docs.datadoghq.com/security/application_security/ を参照

## 5. monitorモードからblockingモードへの変更

Datadog コンソール > Security > Application Security >
WAF Custom Rules から各ルールの "blocking" を有効化してください。
`;
}

// ─────────────────────────────────────────────
// SIEM — Security Information and Event Management
// ─────────────────────────────────────────────

export interface SiemRuleDef {
  name: string;
  query: string;
  groupByFields: string[];
  status: SiemRuleStatus;
  /** Threshold condition, e.g. "a > 0" */
  condition: string;
  message: string;
}

export interface SiemPackDef {
  label: string;
  count: number;
  rules: readonly SiemRuleDef[];
}

/** Cloud security detection rules (CloudTrail-based) */
export const SIEM_CLOUD_RULES: readonly SiemRuleDef[] = [
  {
    name: "不正APIコール検出",
    query:
      "source:cloudtrail @eventName:(DeleteBucket OR DeleteTrail OR StopLogging) @errorCode:Success",
    groupByFields: ["@userIdentity.arn"],
    status: "high",
    condition: "a > 0",
    message:
      "不正なAPIコール (@eventName) が検出されました。ユーザー: @userIdentity.arn",
  },
  {
    name: "権限昇格の試み",
    query:
      "source:cloudtrail @eventName:(AttachUserPolicy OR AttachRolePolicy OR CreatePolicy) @errorCode:Success",
    groupByFields: ["@userIdentity.arn"],
    status: "high",
    condition: "a > 0",
    message:
      "権限昇格の試みが検出されました。アクション: @eventName、ユーザー: @userIdentity.arn",
  },
  {
    name: "クラウドリソース大量削除",
    query: "source:cloudtrail @eventName:Delete* @errorCode:Success",
    groupByFields: ["@userIdentity.arn"],
    status: "medium",
    condition: "a > 20",
    message:
      "短時間にクラウドリソースの大量削除が発生しました。ユーザー: @userIdentity.arn",
  },
] as const;

/** Authentication anomaly detection rules */
export const SIEM_AUTH_RULES: readonly SiemRuleDef[] = [
  {
    name: "ブルートフォース攻撃検出",
    query: "source:auth @evt.outcome:failure",
    groupByFields: ["@network.client.ip"],
    status: "high",
    condition: "a > 10",
    message:
      "ブルートフォース攻撃の疑いがあります。送信元IP: @network.client.ip",
  },
  {
    name: "異常ログイン（新規国からのアクセス）",
    query: "source:auth @evt.outcome:success",
    groupByFields: ["@usr.name", "@network.client.geoip.country.iso_code"],
    status: "medium",
    condition: "a > 0",
    message:
      "通常と異なる国からのログインが検出されました。ユーザー: @usr.name、国: @network.client.geoip.country.iso_code",
  },
  {
    name: "特権アカウントへの異常アクセス",
    query:
      "source:auth @usr.name:(root OR admin OR administrator) @evt.outcome:success",
    groupByFields: ["@network.client.ip"],
    status: "high",
    condition: "a > 0",
    message:
      "特権アカウントへのアクセスが検出されました。IP: @network.client.ip",
  },
] as const;

/** Network threat detection rules */
export const SIEM_NETWORK_RULES: readonly SiemRuleDef[] = [
  {
    name: "ポートスキャン検出",
    query:
      "source:firewall @evt.name:connection @network.destination.port:*",
    groupByFields: ["@network.client.ip"],
    status: "medium",
    condition: "a > 100",
    message: "ポートスキャンの疑いがあります。送信元IP: @network.client.ip",
  },
  {
    name: "不審な外部通信",
    query:
      "source:firewall @direction:outbound @network.bytes_written:>10000000",
    groupByFields: ["@network.client.ip", "@network.destination.ip"],
    status: "high",
    condition: "a > 0",
    message:
      "大量のデータが外部に送信されています。送信元: @network.client.ip、送信先: @network.destination.ip",
  },
] as const;

/** Application-layer attack detection rules */
export const SIEM_APP_RULES: readonly SiemRuleDef[] = [
  {
    name: "SQLインジェクション検出",
    query:
      "source:nginx @http.url_details.path:* (@http.url_details.queryString:*SELECT* OR @http.url_details.queryString:*UNION* OR @http.url_details.queryString:*DROP*)",
    groupByFields: ["@network.client.ip"],
    status: "high",
    condition: "a > 0",
    message:
      "SQLインジェクションの試みが検出されました。送信元IP: @network.client.ip",
  },
  {
    name: "XSS攻撃検出",
    query: "source:nginx @http.url_details.queryString:*<script*",
    groupByFields: ["@network.client.ip"],
    status: "high",
    condition: "a > 0",
    message: "XSS攻撃の試みが検出されました。送信元IP: @network.client.ip",
  },
] as const;

/** All SIEM detection rule packs keyed by pack ID */
export const SIEM_PACKS: Record<SiemPack, SiemPackDef> = {
  cloud: {
    label: "クラウドセキュリティ (不正APIコール, 権限昇格)",
    count: 3,
    rules: SIEM_CLOUD_RULES,
  },
  auth: {
    label: "認証セキュリティ (ブルートフォース, 異常ログイン)",
    count: 3,
    rules: SIEM_AUTH_RULES,
  },
  network: {
    label: "ネットワーク (ポートスキャン)",
    count: 2,
    rules: SIEM_NETWORK_RULES,
  },
  app: {
    label: "アプリケーション (SQLi, XSS)",
    count: 2,
    rules: SIEM_APP_RULES,
  },
} as const;

/** Default SIEM rule evaluation options */
export const SIEM_DEFAULT_OPTIONS = {
  /** Sliding window for evaluation in seconds (5 minutes) */
  evaluationWindow: 300,
  /** How long a signal stays alive in seconds (1 hour) */
  keepAlive: 3600,
  /** Maximum signal duration in seconds (24 hours) */
  maxSignalDuration: 86400,
} as const;

/** Datadog resource type identifier for SIEM rules */
export const SIEM_RULE_TYPE = "log_detection" as const;

// ─────────────────────────────────────────────
// Sensitive Data Scanner
// ─────────────────────────────────────────────

export type SensitiveDataActionType = "mask" | "hash" | "notify";

export interface SensitiveDataPatternDef {
  value: SensitiveDataPattern;
  name: string;
  /** Whether the pattern is selected by default */
  defaultChecked: boolean;
  /** Keywords used to fuzzy-match Datadog standard patterns */
  matchKeywords: string[];
  /** Fallback regex when no standard pattern is found via keyword matching */
  fallbackRegex: string;
}

export interface SensitiveDataActionDef {
  value: SensitiveDataActionType;
  name: string;
  /** Datadog API textReplacement.type value */
  apiType: string;
}

/**
 * Sensitive data pattern definitions with regex fallbacks.
 * matchKeywords are used to search Datadog's standard pattern library.
 * fallbackRegex is applied when no standard pattern matches.
 */
export const SENSITIVE_DATA_PATTERNS: readonly SensitiveDataPatternDef[] = [
  {
    value: "pii",
    name: "個人情報 (氏名, 住所, マイナンバー)",
    defaultChecked: true,
    matchKeywords: ["name", "address", "my number", "マイナンバー", "個人", "住所", "氏名"],
    fallbackRegex: "\\b[\\p{L}\\p{M}]+\\s+[\\p{L}\\p{M}]+\\b",
  },
  {
    value: "credit-card",
    name: "クレジットカード番号",
    defaultChecked: true,
    matchKeywords: ["credit card", "visa", "mastercard", "card number", "クレジット"],
    fallbackRegex:
      "\\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13})\\b",
  },
  {
    value: "api-key",
    name: "APIキー・トークン",
    defaultChecked: true,
    matchKeywords: ["api key", "api token", "access token", "secret key", "トークン"],
    fallbackRegex:
      "(?i)(?:api[_-]?key|token|secret)[\"'\\s]*[:=][\"'\\s]*[\\w\\-]{16,}",
  },
  {
    value: "email",
    name: "メールアドレス",
    defaultChecked: false,
    matchKeywords: ["email", "e-mail", "メール"],
    fallbackRegex: "\\b[a-zA-Z0-9._%+\\-]+@[a-zA-Z0-9.\\-]+\\.[a-zA-Z]{2,}\\b",
  },
  {
    value: "phone",
    name: "電話番号",
    defaultChecked: false,
    matchKeywords: ["phone", "telephone", "電話"],
    fallbackRegex:
      "\\b(?:\\+81|0)[\\-\\s]?\\d{1,4}[\\-\\s]?\\d{1,4}[\\-\\s]?\\d{4}\\b",
  },
] as const;

/** Action options for sensitive data detections */
export const SENSITIVE_DATA_ACTIONS: readonly SensitiveDataActionDef[] = [
  { value: "mask", name: "マスク", apiType: "replacement_string" },
  { value: "hash", name: "ハッシュ化", apiType: "hash" },
  { value: "notify", name: "通知のみ", apiType: "none" },
] as const;

/** Maps action type to Datadog API textReplacement.type */
export const SENSITIVE_DATA_ACTION_TYPE_MAP: Record<SensitiveDataActionType, string> = {
  mask: "replacement_string",
  hash: "hash",
  notify: "none",
} as const;

/** Replacement string used when action is "mask" */
export const SENSITIVE_DATA_MASK_REPLACEMENT = "****" as const;

/** Product list for the scanning group (currently logs only) */
export const SENSITIVE_DATA_PRODUCT_LIST = ["logs"] as const;

/** Default filter query — scan all logs */
export const SENSITIVE_DATA_DEFAULT_FILTER_QUERY = "*" as const;
